baseURL = 'https://smjune.github.io/'
languageCode = 'en-us'
title = 'MyoungJune Sung says Hello Wrold'
theme ='hugo-book'

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'
