image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - cd Hugo                                       # hugo 설치 폴더로 이동 
  - rm config.toml                                # 기존 (github 용) config 삭제
  - cp config_gitlab.toml config.toml             # gitlab용 config 복사
  - hugo --minify                                 # hugo build
  artifacts:
    paths:
    - Hugo/public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
