name: GitHub Pages

on:
  push:
#    branches:
#      - main  # Set a branch to deploy
     paths:
       - '.github/workflows/gh-pages.yml'
       - 'Hugo/**'
  pull_request:

permissions:
  contents: write  # avoid getting '/usr/bin/git' failed with exit code 128 at first

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0' #latest #'0.110.0'  # 145 이후 tag 링크 오류 존재
          extended: true

      - name: Build
        run: |
          cd Hugo                  
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Hugo/public
